[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

  # Evita di scansionare l'output e il file guida (se contiene valori reali)
  SECRETS_SCAN_OMIT_PATHS = "dist/**"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"